// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"BulletHell","status":true,"description":"Simple Bullet hell shoot 'em up engine.","parameters":{"config":"BulletHell.json","resume":"Resume","retry":"Retry","deadzone":"Analog deadzone","speed_multiplier":"Analog scale","quit":"Quit","yes":"Yes","no":"No","speed":"Speed","rate":"Rate","power":"Power","bombs":"Bombs","autobombs":"Autobombs","buy_players":"Players","buy_upgrade":"Upgrades","init_bgm":"Theme1","victory_me":"Victory1","bullet":"$Bullets","explosion":"$Explosions","life_bonus_first":"30000","life_bonus_next":"80000","DCprice":"5000","CBprice":"10000","BAprice":"50000","ASprice":"100000"}},
{"name":"darklord","status":true,"description":"","parameters":{}},
{"name":"rammer","status":true,"description":"","parameters":{}},
{"name":"telefragger","status":true,"description":"","parameters":{}},
{"name":"teleport","status":true,"description":"","parameters":{}},
{"name":"bomb_thunder","status":true,"description":"","parameters":{}},
{"name":"bomb_gravity","status":true,"description":"","parameters":{}},
{"name":"emitter_probe","status":true,"description":"","parameters":{}},
{"name":"emitter_circle","status":true,"description":"","parameters":{}}
];
